/**
 * Redirects from the old WordPress URLs to the new Latin-slug routes.
 *
 * Generated by `npm run migrate` — do not edit by hand.
 */
export type LegacyRedirect = {
  source: string;
  destination: string;
  permanent: boolean;
};

export const legacyRedirects: LegacyRedirect[] = [
  {
    "source": "/category/covid-19",
    "destination": "/nea/kategoria/covid-19",
    "permanent": true
  },
  {
    "source": "/category/αγγλικά",
    "destination": "/nea/kategoria/anglika",
    "permanent": true
  },
  {
    "source": "/category/ανακοινώσεις",
    "destination": "/nea/kategoria/anakoinoseis",
    "permanent": true
  },
  {
    "source": "/category/γαλλικά",
    "destination": "/nea/kategoria/gallika",
    "permanent": true
  },
  {
    "source": "/category/uncategorized",
    "destination": "/nea/kategoria/genika",
    "permanent": true
  },
  {
    "source": "/category/γενική-ενημέρωση",
    "destination": "/nea/kategoria/geniki-enimerosi",
    "permanent": true
  },
  {
    "source": "/category/γυμναστική",
    "destination": "/nea/kategoria/gymnastiki",
    "permanent": true
  },
  {
    "source": "/category/δήμος-αγίας-παρασκευής",
    "destination": "/nea/kategoria/dimos-agias-paraskefis",
    "permanent": true
  },
  {
    "source": "/category/διακρίσεις",
    "destination": "/nea/kategoria/diakriseis",
    "permanent": true
  },
  {
    "source": "/category/δράσεις",
    "destination": "/nea/kategoria/draseis",
    "permanent": true
  },
  {
    "source": "/category/εκπαιδευτική-τηλεόραση",
    "destination": "/nea/kategoria/ekpaideftiki-tileorasi",
    "permanent": true
  },
  {
    "source": "/category/εξ-αποστάσεως-διδασκαλία",
    "destination": "/nea/kategoria/ex-apostaseos-didaskalia",
    "permanent": true
  },
  {
    "source": "/category/θέματα-υγείας",
    "destination": "/nea/kategoria/themata-ygeias",
    "permanent": true
  },
  {
    "source": "/category/ιστορική-επέτειος",
    "destination": "/nea/kategoria/istoriki-epeteios",
    "permanent": true
  },
  {
    "source": "/category/παγκόσμιες-ημέρες",
    "destination": "/nea/kategoria/pagkosmies-imeres",
    "permanent": true
  },
  {
    "source": "/category/πληροφορική",
    "destination": "/nea/kategoria/pliroforiki",
    "permanent": true
  },
  {
    "source": "/category/πολιτισμός",
    "destination": "/nea/kategoria/politismos",
    "permanent": true
  },
  {
    "source": "/category/προσωπικά-δεδομένα",
    "destination": "/nea/kategoria/prosopika-dedomena",
    "permanent": true
  },
  {
    "source": "/category/σχολικές-δραστηριότητες",
    "destination": "/nea/kategoria/scholikes-drastiriotites",
    "permanent": true
  },
  {
    "source": "/category/ψυχολογικά-θέματα",
    "destination": "/nea/kategoria/psychologika-themata",
    "permanent": true
  },
  {
    "source": "/πληροφορίες",
    "destination": "/to-scholeio-mas",
    "permanent": true
  },
  {
    "source": "/sample-page/μήνυμα-της-διεύθυνσης",
    "destination": "/minyma-tis-diefthynsis",
    "permanent": true
  },
  {
    "source": "/ιστορία-εγκαταστάσεις",
    "destination": "/genikes-plirofories",
    "permanent": true
  },
  {
    "source": "/διδακτικό-προσωπικό",
    "destination": "/didaktiko-prosopiko",
    "permanent": true
  },
  {
    "source": "/ορια-του-σχολείου-μας",
    "destination": "/oria-tou-scholeiou",
    "permanent": true
  },
  {
    "source": "/sample-page/διάφορα-έντυπα",
    "destination": "/diafora-entypa",
    "permanent": true
  },
  {
    "source": "/σχολική-ζωή",
    "destination": "/scholiki-zoi",
    "permanent": true
  },
  {
    "source": "/κανονισμός-του-σχολείου",
    "destination": "/kanonismos",
    "permanent": true
  },
  {
    "source": "/πληροφορίες-για-το-ολοήμερο",
    "destination": "/oloimero",
    "permanent": true
  },
  {
    "source": "/σχολικές-εκδηλώσεις",
    "destination": "/scholikes-ekdiloseis",
    "permanent": true
  },
  {
    "source": "/εκπαιδευτικές-επισκέψεις",
    "destination": "/ekpaideftikes-episkepseis",
    "permanent": true
  },
  {
    "source": "/δράσεις",
    "destination": "/draseis",
    "permanent": true
  },
  {
    "source": "/αιτηση-εγγραφησ-στο-σχολειο-μασ",
    "destination": "/aitisi-eggrafis",
    "permanent": true
  },
  {
    "source": "/2020/03/21/νέος-δικτυακός-τόπος-του-8ου-δημοτικού",
    "destination": "/nea/neos-diktyakos-topos-tou-8ou-dimotikoy-agias-paraskefis-dokimastiki",
    "permanent": true
  },
  {
    "source": "/2020/03/22/μένουμε-σπίτι",
    "destination": "/nea/menoume-spiti",
    "permanent": true
  },
  {
    "source": "/2020/03/22/οδηγίες-για-την-εξαποστάσεως-εκπαίδε",
    "destination": "/nea/odigies-gia-tin-exapostaseos-ekpaidefsi",
    "permanent": true
  },
  {
    "source": "/2020/03/23/μήνυμα-των-διδασκόντων",
    "destination": "/nea/minyma-ton-didaskonton",
    "permanent": true
  },
  {
    "source": "/2020/03/24/ενημέρωση-για-το-email",
    "destination": "/nea/enimerosi-gia-to-email",
    "permanent": true
  },
  {
    "source": "/2020/03/24/εγγραφή-στο-πανελλήνιο-σχολικό-δίκτυ",
    "destination": "/nea/engrafi-sto-panellinio-scholiko-diktyo",
    "permanent": true
  },
  {
    "source": "/2020/03/24/25η-μαρτίου-η-ελλάδα-γιορτάζει-διπλά",
    "destination": "/nea/25i-martiou-1821-i-ellada-giortazei-dipla",
    "permanent": true
  },
  {
    "source": "/2020/03/25/παράταση-εγγραφών-εκπαιδευτικών-μαθ",
    "destination": "/nea/paratasi-engrafon-ekpaideftikon-mathiton-sto-panellinio-scholiko-diktyo",
    "permanent": true
  },
  {
    "source": "/2020/03/27/μένουμε-σπίτι-συνδε-∆εμένοι",
    "destination": "/nea/menoume-spiti-synde-emenoi",
    "permanent": true
  },
  {
    "source": "/2020/03/27/ενημέρωση-για-εξ-αποστάσεως-επικοινω",
    "destination": "/nea/enimerosi-gia-ex-apostaseos-epikoinonia-ypostirixi-apo-to-2o-kesy",
    "permanent": true
  },
  {
    "source": "/2020/03/27/πολιτική-προστασίας-προσωπικών-δεδο",
    "destination": "/nea/politiki-prostasias-prosopikon-dedomenon-sto-panellinio-scholiko-diktyo",
    "permanent": true
  },
  {
    "source": "/2020/03/27/μήνυμα-από-τη-δασκάλα-της-μουσικής",
    "destination": "/nea/minyma-apo-ti-daskala-tis-mousikis",
    "permanent": true
  },
  {
    "source": "/2020/03/28/eιδική-τηλεοπτική-ζώνη-εξ-αποστάσεως-μ",
    "destination": "/nea/eidiki-tileoptiki-zoni-ex-apostaseos-mathimaton-stin-ert2",
    "permanent": true
  },
  {
    "source": "/2020/03/28/ψηφιακή-εκπαιδευτική-πλατφόρμα-e-me",
    "destination": "/nea/psifiaki-ekpaideftiki-platforma-e-me",
    "permanent": true
  },
  {
    "source": "/2020/03/29/μήνυμα-από-τη-δασκάλα-των-γαλλικών",
    "destination": "/nea/minyma-apo-ti-daskala-ton-gallikon",
    "permanent": true
  },
  {
    "source": "/2020/03/29/28-μαρτίου-παγκόσμια-ημέρα-θεάτρου-σκιώ",
    "destination": "/nea/28-martiou-pagkosmia-imera-theatrou-skion",
    "permanent": true
  },
  {
    "source": "/2020/03/30/μαθαίνουμε-στο-σπίτι",
    "destination": "/nea/mathainoume-sto-spiti",
    "permanent": true
  },
  {
    "source": "/2020/03/31/μήνυμα-από-τον-γυμναστή-κ-γιάννη",
    "destination": "/nea/minyma-apo-ton-gymnasti-k-gianni",
    "permanent": true
  },
  {
    "source": "/2020/04/02/παγκόσμια-ημέρα-παιδικού-βιβλίου",
    "destination": "/nea/pagkosmia-imera-paidikoy-vivliou",
    "permanent": true
  },
  {
    "source": "/2020/04/02/παγκόσμια-ημέρα-αυτισμού",
    "destination": "/nea/2-apriliou-pagkosmia-imera-aftismoy",
    "permanent": true
  },
  {
    "source": "/2020/04/04/πώς-θα-βοηθήσουμε-παιδιά-και-εφήβους-τ",
    "destination": "/nea/pos-tha-voithisoume-paidia-kai-efivous-tora-pou-menoume-spiti",
    "permanent": true
  },
  {
    "source": "/2020/04/06/ιστορική-επέτειος-6-απριλίου-1941-η-μάχη-τω",
    "destination": "/nea/istoriki-epeteios-6-apriliou-1941-i-machi-ton-ochyron-6-eos-10-apriliou",
    "permanent": true
  },
  {
    "source": "/2020/04/06/μαθαίνουμε-στο-σπίτι-πρόγραμμα-εκπαι",
    "destination": "/nea/programma-ekpaideftikis-tileorasis-stin-ert2-evdomada-6-10-apriliou-2020",
    "permanent": true
  },
  {
    "source": "/2020/04/09/σύνδεσμοι-από-μουσεία-και-άλλους-φορε",
    "destination": "/nea/syndesmoi-apo-mouseia-kai-allous-foreis-me-ekpaideftiko-yliko-kai",
    "permanent": true
  },
  {
    "source": "/2020/04/14/προγραμμa-εκπαιδευτικησ-τηλεορασησ-ε",
    "destination": "/nea/programma-ekpaideftikis-tileorasis-stin-ert2-megali-evdomada",
    "permanent": true
  },
  {
    "source": "/2020/04/26/πρόγραμμα-εκπαιδευτικής-τηλεόρασης",
    "destination": "/nea/programma-ekpaideftikis-tileorasis-stin-ert2-27-4-30-4",
    "permanent": true
  },
  {
    "source": "/2020/04/26/πρόσκληση-γονέων-κηδεμόνων-μαθητών-τ",
    "destination": "/nea/prosklisi-goneon-kidemonon-mathiton-trion-kathe-vathmidas-se",
    "permanent": true
  },
  {
    "source": "/2020/05/04/πρόγραμμα",
    "destination": "/nea/programma-ekpaideftikis-tileorasis-stin-ert2-4-5-8-5",
    "permanent": true
  },
  {
    "source": "/2020/05/07/πρόσκληση-σε-διαδικτυακή-συνάντηση-σ",
    "destination": "/nea/prosklisi-se-diadiktyaki-synantisi-syndesis-kai-endynamosis-me-titlo",
    "permanent": true
  },
  {
    "source": "/2020/05/07/διαδικασία-εισαγωγής-μαθητών-στην-α",
    "destination": "/nea/diadikasia-eisagogis-mathiton-stin-a-taxi-gymnasiou-ton-mousikon-kai",
    "permanent": true
  },
  {
    "source": "/2020/05/10/ψυχική-υγεία-των-παιδιών-εν-μέσω-της-πα",
    "destination": "/nea/psychiki-ygeia-ton-paidion-en-meso-tis-pandimias-covid-19-odigos-gia",
    "permanent": true
  },
  {
    "source": "/2020/05/10/ημέρα-της-μητέρας-2020",
    "destination": "/nea/imera-tis-miteras-2020",
    "permanent": true
  },
  {
    "source": "/2020/05/14/εγγραφές-στην-α΄δημοτικού-για-το-σχ-έτ",
    "destination": "/nea/engrafes-stin-adimotikoy-gia-to-scholiko-etos-2020-2021",
    "permanent": true
  },
  {
    "source": "/2020/05/17/ερωτηματολόγιο-σχετικά-με-την-εκπαίδ",
    "destination": "/nea/erotimatologio-schetika-me-tin-ekpaidefsi-stin-psifiaki-politeiotita",
    "permanent": true
  },
  {
    "source": "/2020/05/24/πρόγραμμα-εκπαιδευτικής-τηλεόρασης-2",
    "destination": "/nea/programma-ekpaideftikis-tileorasis-stin-ert2-25-29-5-2020",
    "permanent": true
  },
  {
    "source": "/2020/05/26/ανακοίνωση",
    "destination": "/nea/anakoinosi",
    "permanent": true
  },
  {
    "source": "/2020/05/29/λοίμωξη-από-το-νέο-κορωνοϊό-sars-cov-2-covid-19-οδηγί",
    "destination": "/nea/loimoxi-apo-to-neo-koronoio-sars-cov-2-covid-19-odigies-gia-dimotika",
    "permanent": true
  },
  {
    "source": "/2020/05/29/κανονισμός-λειτουργίας-του-8ου-δημοτι",
    "destination": "/nea/kanonismos-leitourgias-tou-8ou-dimotikoy-scholeiou-agias-paraskefis",
    "permanent": true
  },
  {
    "source": "/2020/06/11/εγγραφή-μαθητών-στα-ολοήμερα-τμήματα",
    "destination": "/nea/engrafi-mathiton-sta-oloimera-tmimata-tou-scholeiou-gia-to-sch-etos",
    "permanent": true
  },
  {
    "source": "/2020/06/16/εισαγωγή-μαθητών-τριών-και-σχετικές-ρ",
    "destination": "/nea/eisagogi-mathiton-trion-kai-schetikes-rythmiseis-sta-protypa-kai",
    "permanent": true
  },
  {
    "source": "/2020/06/22/ανακοίνωση-για-παιδικές-κατασκηνώσε",
    "destination": "/nea/anakoinosi-gia-paidikes-kataskinoseis-2020",
    "permanent": true
  },
  {
    "source": "/2020/06/23/τίτλοι-προόδου-και-σπουδών",
    "destination": "/nea/titloi-proodou-kai-spoudon",
    "permanent": true
  },
  {
    "source": "/2020/08/26/απαλλαγή-από-το-μάθημα-των-θρησκευτικ",
    "destination": "/nea/apallagi-apo-to-mathima-ton-thriskeftikon",
    "permanent": true
  },
  {
    "source": "/2020/09/08/ανακοίνωση-για-θεσμό-σχολικού-τροχον",
    "destination": "/nea/anakoinosi-gia-thesmo-scholikoy-trochonomou",
    "permanent": true
  },
  {
    "source": "/2020/09/09/οδηγίες-για-δημοτικά-σχολεία-covid-19",
    "destination": "/nea/odigies-gia-dimotika-scholeia-gia-ton-covid-19",
    "permanent": true
  },
  {
    "source": "/2020/09/11/αγιασμός-προσέλευση",
    "destination": "/nea/agiasmos-proselefsi",
    "permanent": true
  },
  {
    "source": "/2020/09/18/οδηγίες-για-τη-σύγχρονη-εξ-αποστάσεως",
    "destination": "/nea/odigies-gia-ti-synchroni-ex-apostaseos-ekpaidefsi-kata-to-scholiko-etos",
    "permanent": true
  },
  {
    "source": "/2020/11/18/ανακοίνωση-από-τους-δασκάλους",
    "destination": "/nea/anakoinosi-apo-tous-daskalous",
    "permanent": true
  },
  {
    "source": "/2020/11/18/γιάννης-ρίτσος-16-και-17-νοέμβρη-1973",
    "destination": "/nea/giannis-ritsos-16-kai-17-noemvri-1973",
    "permanent": true
  },
  {
    "source": "/2020/11/18/οδηγίες-για-τη-χρήση-της-εξ-αποστάσεως",
    "destination": "/nea/odigies-gia-ti-chrisi-tis-ex-apostaseos-didaskalias",
    "permanent": true
  },
  {
    "source": "/2020/11/18/ανακοίνωση-σχετικά-με-εξοπλισμό-η-υ",
    "destination": "/nea/anakoinosi-schetika-me-exoplismo-i-y",
    "permanent": true
  },
  {
    "source": "/2020/11/23/ευχαριστήρια-επιστολή",
    "destination": "/nea/efcharistiria-epistoli",
    "permanent": true
  },
  {
    "source": "/2020/11/27/ανακοίνωση-για-τους-μαθητές-που-φοιτο",
    "destination": "/nea/anakoinosi-gia-tous-mathites-pou-foitoyn-stin-stkai-tous-goneis-tous",
    "permanent": true
  },
  {
    "source": "/2020/12/24/καλα-χριστουγεννα",
    "destination": "/nea/kala-christougenna",
    "permanent": true
  },
  {
    "source": "/2021/02/27/εγγραφές-στην-α΄δημοτικού-για-το-σχ-έτ-2",
    "destination": "/nea/engrafes-stin-adimotikoy-gia-to-sch-etos-2021-2022",
    "permanent": true
  },
  {
    "source": "/2021/03/05/εβδομαδιαίος-μαθητικός-αγώνας-υγεία",
    "destination": "/nea/evdomadiaios-mathitikos-agonas-ygeias-kai-dynamikoy-vadismatos",
    "permanent": true
  },
  {
    "source": "/2021/03/07/μήνυμα-της-υπουργού-παιδείας-και-θρησ",
    "destination": "/nea/minyma-tis-ypourgoy-paideias-kai-thriskefmaton-gia-tin-6i-martiou",
    "permanent": true
  },
  {
    "source": "/2021/03/09/διαγωνισμός-γαλλοφωνίας-2021-α1-atlantis",
    "destination": "/nea/diagonismos-gallofonias-2021-a1-atlantis",
    "permanent": true
  },
  {
    "source": "/2021/03/13/επιστολή-προς-το-σύλλογο-γονέων",
    "destination": "/nea/epistoli-pros-to-syllogo-goneon",
    "permanent": true
  },
  {
    "source": "/2021/03/20/ενημέρωση-για-εγγραφές-στην-α-δημοτικ",
    "destination": "/nea/enimerosi-gia-engrafes-stin-a-dimotikoy",
    "permanent": true
  },
  {
    "source": "/2021/03/20/ενημέρωση-για-το-τμήμα-ένταξης",
    "destination": "/nea/enimerosi-gia-to-tmima-entaxis",
    "permanent": true
  },
  {
    "source": "/2021/05/05/διαδικασία-προμήθειας-και-διενέργει",
    "destination": "/nea/diadikasia-promitheias-kai-dienergeia-tou-diagnostikoy-elenchou-nosisis",
    "permanent": true
  },
  {
    "source": "/2021/05/07/επιστρέφουμε-με-ασφάλεια-στο-σχολείο",
    "destination": "/nea/epistrefoume-me-asfaleia-sto-scholeio-odigies-gia-ta-self-test",
    "permanent": true
  },
  {
    "source": "/2021/05/21/3ο-μαθητικό-φεστιβάλ-ρητορικής-τέχνης",
    "destination": "/nea/3o-mathitiko-festival-ritorikis-technis",
    "permanent": true
  },
  {
    "source": "/2021/05/27/συμμετοχή-στο-3ο-μαθητικό-φεστιβάλ-ρητ",
    "destination": "/nea/symmetochi-sto-3o-mathitiko-festival-ritorikis-technis",
    "permanent": true
  },
  {
    "source": "/2021/06/04/a-whales-tale-digital-storybook-εργασία-τμήματος-ε1",
    "destination": "/nea/a-whales-tale-digital-storybook-ergasia-tmimatos-e1",
    "permanent": true
  },
  {
    "source": "/2021/06/04/ανακοίνωση-του-δήμου-αγίας-παρασκευή",
    "destination": "/nea/anakoinosi-tou-dimou-agias-paraskefis-gia-paidikes-kataskinoseis-2021",
    "permanent": true
  },
  {
    "source": "/2021/06/05/θερινό-πρόγραμμα-ημερήσιας-δημιουργ",
    "destination": "/nea/therino-programma-imerisias-dimiourgikis-apascholisis-2021-apo-ton-dimo",
    "permanent": true
  },
  {
    "source": "/2021/06/22/πρόγραμμα-ψηφιακή-μέριμνα",
    "destination": "/nea/programma-psifiaki-merimna",
    "permanent": true
  },
  {
    "source": "/2021/06/22/φτάνοντας-στο-τέλος-της-σχολικής-χρον",
    "destination": "/nea/ftanontas-sto-telos-tis-scholikis-chronias",
    "permanent": true
  },
  {
    "source": "/2021/06/28/project-ιστορικής-αφήγησης-για-στο-μάθημα-αγ",
    "destination": "/nea/project-istorikis-afigisis-sto-mathima-anglikon-tis-sttaxis",
    "permanent": true
  },
  {
    "source": "/2021/06/28/συμμετοχή-στον-διαγωνισμό-γαλλοφωνί",
    "destination": "/nea/symmetochi-ston-diagonismo-gallofonias-2021",
    "permanent": true
  },
  {
    "source": "/2021/09/09/υλικά-μαθητών-για-το-σχολείο-ανά-τάξη-ή",
    "destination": "/nea/ylika-mathiton-gia-to-scholeio-ana-taxi-i-tmima",
    "permanent": true
  },
  {
    "source": "/2021/09/09/σημαντική-ενημέρωση-για-την-έναρξη-τη",
    "destination": "/nea/simantiki-enimerosi-gia-tin-enarxi-tis-scholikis-chronias",
    "permanent": true
  },
  {
    "source": "/2021/09/28/open-air-cinema-στον-δήμο-αγίας-παρασκευής",
    "destination": "/nea/open-air-cinema-ston-dimo-agias-paraskefis",
    "permanent": true
  },
  {
    "source": "/2021/10/30/ενημέρωση-για-το-edupass-gov-gr",
    "destination": "/nea/enimerosi-gia-to-edupass-gov-gr",
    "permanent": true
  },
  {
    "source": "/2021/12/14/έλεγχοι-προόδου-για-το-α-τρίμηνο",
    "destination": "/nea/elenchoi-proodou-gia-to-a-trimino",
    "permanent": true
  },
  {
    "source": "/2022/01/05/οδηγίες-για-τον-covid",
    "destination": "/nea/odigies-gia-ton-covid",
    "permanent": true
  },
  {
    "source": "/2022/01/18/συνοπτικός-οδηγός-αντιμετώπισης-covid-γι",
    "destination": "/nea/synoptikos-odigos-antimetopisis-covid-gia-ta-scholeia",
    "permanent": true
  },
  {
    "source": "/2022/03/09/διάκριση-μαθητή-του-σχολείου-μας",
    "destination": "/nea/diakrisi-mathiti-tou-scholeiou-mas-sto-diagonismo-henri-poincare",
    "permanent": true
  },
  {
    "source": "/2022/03/11/βαθμολογία-β΄τριμήνου",
    "destination": "/nea/elenchoi-proodou-v-triminou",
    "permanent": true
  },
  {
    "source": "/2022/03/16/εισαγωγή-μαθητών-σε-πρότυπα-ή-πειραμα",
    "destination": "/nea/eisagogi-mathiton-se-protypa-i-peiramatika",
    "permanent": true
  },
  {
    "source": "/2022/03/20/εγγραφές-στην-α΄δημοτικού-για-το-σχ-έτ-3",
    "destination": "/nea/engrafes-stin-adimotikoy-gia-to-sch-etos-2022-2023",
    "permanent": true
  },
  {
    "source": "/2022/03/21/συμμετοχή-και-διακρίσεις-στο-διαγωνι",
    "destination": "/nea/symmetochi-kai-diakriseis-sto-diagonismo-logikomathimatikis-skepsis",
    "permanent": true
  },
  {
    "source": "/2022/03/28/οδοντιατρικός-έλεγχος-μαθητών-του-σχ",
    "destination": "/nea/odontiatrikos-elenchos-mathiton-tou-scholeiou-mas",
    "permanent": true
  },
  {
    "source": "/2022/05/01/νέο-πρωτόκολλο-διαχείρισης-covid-και-αντι",
    "destination": "/nea/neo-protokollo-diacheirisis-covid-kai-antimetopisis-krousmaton-sta",
    "permanent": true
  },
  {
    "source": "/2022/05/05/θερινό-πρόγραμμα-ημερήσιας-δημιουργ-2",
    "destination": "/nea/therino-programma-imerisias-dimiourgikis-apascholisis-tou-dimou-agias",
    "permanent": true
  },
  {
    "source": "/2022/05/30/ανακοίνωση-για-παιδικές-κατασκηνώσε-2",
    "destination": "/nea/anakoinosi-gia-paidikes-kataskinoseis-2022",
    "permanent": true
  },
  {
    "source": "/2022/09/02/αίτηση-γονέα-κηδεμόνα-για-νέο-ολοήμερ",
    "destination": "/nea/aitisi-gonea-kidemona-gia-neo-oloimero",
    "permanent": true
  },
  {
    "source": "/2022/09/08/test",
    "destination": "/nea/ylika-mathiton-gia-to-scholeio-ana-taxi-i-tmima-2",
    "permanent": true
  },
  {
    "source": "/2022/10/01/30-09-22-πανελλήνια-ημέρα-σχολικού-αθλητισμ",
    "destination": "/nea/30-09-22-panellinia-imera-scholikoy-athlitismoy",
    "permanent": true
  },
  {
    "source": "/2022/10/10/ευχαριστήρια-επιστολή-για-τη-χορηγία",
    "destination": "/nea/efcharistiria-epistoli-gia-tin-chorigia-tis-aon-greece-s-a",
    "permanent": true
  },
  {
    "source": "/2022/10/19/18-10-22-eπίσκεψη-της-στ΄-τάξης-στην-ακρόπολη",
    "destination": "/nea/18-10-22-episkepsi-tis-st-taxis-stin-akropoli",
    "permanent": true
  },
  {
    "source": "/2022/10/27/εορτασμοσ-επετειου-28ης-οκτωβριου-στο-δ",
    "destination": "/nea/eortasmos-epeteiou-28is-oktovriou-sto-dimotiko-mas",
    "permanent": true
  },
  {
    "source": "/2022/11/11/επισκεψη-συγγραφεων-στο-δημοτικο-μασ",
    "destination": "/nea/08-11-22-episkepsi-syngrafeon-sto-dimotiko-mas",
    "permanent": true
  },
  {
    "source": "/2022/11/14/ανακοινωση-για-τον-εορτασμο-του-πολυτ",
    "destination": "/nea/anakoinosi-gia-ton-eortasmo-tou-polytechneiou",
    "permanent": true
  },
  {
    "source": "/2022/11/17/17-11-2022-εορτασμοσ-του-πολυτεχνειου",
    "destination": "/nea/17-11-2022-eortasmos-tou-polytechneiou",
    "permanent": true
  },
  {
    "source": "/2022/11/22/συμμετοχη-στο-φεστιβαλ-ελληνοκινεζι",
    "destination": "/nea/symmetochi-sto-festival-ellinokinezikis-filias",
    "permanent": true
  },
  {
    "source": "/2022/11/22/codeweek-στο-8ο-δημοτικό-αγίας-παρασκευής",
    "destination": "/nea/efropaiki-evdomada-programmatismoy-sto-8o-dimotiko-agias-paraskefis",
    "permanent": true
  },
  {
    "source": "/2022/12/05/μουσειο-βορρε",
    "destination": "/nea/episkepsi-sto-mouseio-vorre",
    "permanent": true
  },
  {
    "source": "/2022/12/19/τρισδιάστατη-εκτύπωση-ένας-πολιτιστ",
    "destination": "/nea/trisdiastati-ektyposi-enas-politistikos-epitachyntis-gia-tin-ekpaidefsi",
    "permanent": true
  },
  {
    "source": "/2022/12/19/eνημέρωση-γονέων-τρίτη-20-12-22",
    "destination": "/nea/enimerosi-goneon-kai-kidemonon-triti-20-12-22",
    "permanent": true
  },
  {
    "source": "/2023/02/05/πρόγραμμα-τηλεκπαίδευσης",
    "destination": "/nea/programma-tilekpaidefsis",
    "permanent": true
  },
  {
    "source": "/2023/02/08/ανακοινωση",
    "destination": "/nea/anakoinosi-08-02-23",
    "permanent": true
  },
  {
    "source": "/2023/02/08/ανακοινωση-09-02-23",
    "destination": "/nea/anakoinosi-09-02-23",
    "permanent": true
  },
  {
    "source": "/2023/02/20/διάφορα-έντυπα",
    "destination": "/nea/engrafes-stin-a-dimotikoy-gia-to-sch-etos-2023-2024",
    "permanent": true
  },
  {
    "source": "/2023/03/07/επίσκεψη-της-κ-λαζανά-στο-δημοτικό-μας",
    "destination": "/nea/episkepsi-tis-k-lazana-sto-dimotiko-mas",
    "permanent": true
  },
  {
    "source": "/2023/03/07/θεμα-εισαγωγή-μαθητών-στα-πρότυπα-κα",
    "destination": "/nea/thema-eisagogi-mathiton-sta-protypa-kai-peiramatika-scholeia-gia-to-sch",
    "permanent": true
  },
  {
    "source": "/2023/03/16/σημαντική-διάκριση-μαθήτριας-του-σχο",
    "destination": "/nea/simantiki-diakrisi-mathitrias-tou-scholeiou-mas",
    "permanent": true
  },
  {
    "source": "/2023/03/16/ενημερωση-γονεων",
    "destination": "/nea/enimerosi-goneon",
    "permanent": true
  },
  {
    "source": "/2023/03/23/εορτασμός-25ης-μαρτίου",
    "destination": "/nea/eortasmos-25is-martiou",
    "permanent": true
  },
  {
    "source": "/2023/03/27/η-κακοσκουφίτσα-κι-ο-καλόκαρδος-λυκάκ",
    "destination": "/nea/i-kakoskoufitsa-ki-o-kalokardos-lykakos",
    "permanent": true
  },
  {
    "source": "/2023/03/28/eορτασμός-της-25ης-μαρτίου-στο-δημοτικό",
    "destination": "/nea/eortasmos-tis-25is-martiou-sto-dimotiko-mas",
    "permanent": true
  },
  {
    "source": "/2023/04/03/διακριση-για-το-σχολειο",
    "destination": "/nea/diakrisi-gia-to-scholeio",
    "permanent": true
  },
  {
    "source": "/2023/04/03/eθνικός-κήπος",
    "destination": "/nea/episkepsi-ston-ethniko-kipo",
    "permanent": true
  },
  {
    "source": "/2023/04/12/etwinning_1st_web_meeting",
    "destination": "/nea/enarxi-programmatos-etwinning-sto-scholeio-mas-1st-conference-call",
    "permanent": true
  },
  {
    "source": "/2023/04/24/διαδικασία-εισαγωγής-των-μαθητών-στη",
    "destination": "/nea/diadikasia-eisagogis-ton-mathiton-stin-a-taxi-gymnasiou-ton",
    "permanent": true
  },
  {
    "source": "/2023/04/27/science-in-fun",
    "destination": "/nea/science-in-fun",
    "permanent": true
  },
  {
    "source": "/2023/04/27/eπίσκεψη-της-συγγραφέως-κ-μπαχά-στο-σχο",
    "destination": "/nea/episkepsi-tis-syngrafeos-k-bacha-sto-scholeio",
    "permanent": true
  },
  {
    "source": "/2023/05/08/5o-mαθητικό-φεστιβαλ-ρητορικής-τέχνης",
    "destination": "/nea/5o-mathitiko-festival-ritorikis-technis",
    "permanent": true
  },
  {
    "source": "/2023/05/09/θερινο-προγραμμα-ημερησιασ-δημιουργ",
    "destination": "/nea/therino-programma-imerisias-dimiourgikis-apascholisis-2023",
    "permanent": true
  },
  {
    "source": "/2023/05/16/16η-συνάντηση-μαθητικής-δημιουργίας",
    "destination": "/nea/16i-synantisi-mathitikis-dimiourgias",
    "permanent": true
  },
  {
    "source": "/2023/05/25/eπιστολη-επιβραβευσησ-νοwaste21",
    "destination": "/nea/epistoli-epivravefsis-nowaste21",
    "permanent": true
  },
  {
    "source": "/2023/05/26/eπίσκεψη-στο-arena-soccer-center",
    "destination": "/nea/episkepsi-sto-arena-soccer-center",
    "permanent": true
  },
  {
    "source": "/2023/05/29/εγκαινια-σχολικησ-βιβλιοθηκησ",
    "destination": "/nea/egkainia-scholikis-vivliothikis",
    "permanent": true
  },
  {
    "source": "/2023/05/29/2st-web-meeting-10th-of-may-analysis-of-project-progress",
    "destination": "/nea/2st-web-meeting-10th-of-may-analysis-of-project-progress",
    "permanent": true
  },
  {
    "source": "/2023/06/07/θερινα-προγραμματα-κατασκηνωσεων-το",
    "destination": "/nea/therina-programmata-kataskinoseon-tou-dimou-agias-paraskefis",
    "permanent": true
  },
  {
    "source": "/2023/06/13/eπίσκεψη-στο-πνευματικό-κέντρο-ραφήνα",
    "destination": "/nea/episkepsi-sto-pnefmatiko-kentro-rafinas",
    "permanent": true
  },
  {
    "source": "/2023/06/13/tα-δικαιώματα-των-παιδιών-δ΄-τάξη",
    "destination": "/nea/ta-dikaiomata-ton-paidion-d-taxi",
    "permanent": true
  },
  {
    "source": "/2023/06/13/τα-μικρά-απίθανα-μολύβια",
    "destination": "/nea/ta-mikra-apithana-molyvia",
    "permanent": true
  },
  {
    "source": "/2023/06/17/γιορτη-αποφοιτησησ-τησ-στ΄-δημοτικου",
    "destination": "/nea/giorti-apofoitisis-tis-st-dimotikou",
    "permanent": true
  },
  {
    "source": "/2023/06/19/3rd-e-twinning-web-meeting-7th-of-june-presentation-of-results-drawing-conclusions-evaluation",
    "destination": "/nea/3rd-e-twinning-web-meeting-7th-14th-of-june-presentation-of-results",
    "permanent": true
  },
  {
    "source": "/2023/09/08/έναρξη-σχολικής-χρονιάς",
    "destination": "/nea/enarxi-scholikis-chronias",
    "permanent": true
  },
  {
    "source": "/2023/10/24/ρουχα-παρελασησ-28-οκτωβριου",
    "destination": "/nea/roucha-parelasis-28-oktovriou",
    "permanent": true
  },
  {
    "source": "/2023/10/26/εκπαιδευτικές-επισκέψεις",
    "destination": "/nea/ekpaideftikes-episkepseis",
    "permanent": true
  },
  {
    "source": "/2023/10/26/παρέλαση-28ης-οκτωβρίου",
    "destination": "/nea/parelasi-28is-oktovriou",
    "permanent": true
  },
  {
    "source": "/2023/11/08/παιδικός-αγώνας-δρόμου-στο-πλαίσιο-το",
    "destination": "/nea/paidikos-agonas-dromou-sto-plaisio-tou-40ou-marathoniou-o-afthentikos",
    "permanent": true
  },
  {
    "source": "/2023/11/22/2ο-φεστιβάλ-στίβου-δήμου-αγίας-παρασκε",
    "destination": "/nea/2o-festival-stivou-dimou-agias-paraskefis",
    "permanent": true
  },
  {
    "source": "/2023/11/28/σχολικός-ψυχολόγος",
    "destination": "/nea/scholiki-psychologos",
    "permanent": true
  },
  {
    "source": "/2023/12/11/1316",
    "destination": "/nea/epidosi-vathmologias",
    "permanent": true
  },
  {
    "source": "/2023/12/12/3-δεκεμβρίου-παγκόσμια-ημέρα-ατόμων-με",
    "destination": "/nea/3-dekemvriou-pagkosmia-imera-atomon-me-anapiria",
    "permanent": true
  },
  {
    "source": "/2024/01/02/θεατρική-παράσταση-στο-μέγαρο-μουσικ",
    "destination": "/nea/theatriki-parastasi-sto-megaro-mousikis",
    "permanent": true
  },
  {
    "source": "/2024/01/06/δωρεά-βιβλίων-στη-βιβλιοθήκη-του-σχολ",
    "destination": "/nea/dorea-vivlion-stous-mathites-tou-scholeiou-mas",
    "permanent": true
  },
  {
    "source": "/2024/01/06/επίσκεψη-της-συγγραφέως-μάνιας-ζηρίδ",
    "destination": "/nea/episkepsi-tis-syngrafeos-manias-ziridi-sto-scholeio-mas",
    "permanent": true
  },
  {
    "source": "/2024/01/06/secret-santa",
    "destination": "/nea/secret-santa",
    "permanent": true
  },
  {
    "source": "/2024/01/07/εκκλησιασμός-των-μαθητών",
    "destination": "/nea/ekklisiasmos-ton-mathiton",
    "permanent": true
  },
  {
    "source": "/2024/01/07/μύρισαν-χριστούγεννα",
    "destination": "/nea/myrisan-christoygenna",
    "permanent": true
  },
  {
    "source": "/2024/01/08/επίσκεψη-εικογράφου-γεώργιου-σγουρο",
    "destination": "/nea/episkepsi-eikonografou-georgiou-sgouroy-sto-scholeio-mas",
    "permanent": true
  },
  {
    "source": "/2024/01/08/μια-χριστουγεννιάτικη-εβδομάδα-στο-8-δ",
    "destination": "/nea/mia-christougenniatiki-evdomada-sto-8-dimotiko-agias-paraskefis",
    "permanent": true
  },
  {
    "source": "/2024/01/12/εκπαιδευτικές-επισκέψεις-2",
    "destination": "/nea/ekpaideftikes-episkepseis-2",
    "permanent": true
  },
  {
    "source": "/2024/01/14/1459",
    "destination": "/nea/choris-titlo",
    "permanent": true
  },
  {
    "source": "/2024/01/26/ενημέρωση-για-τη-γιορτή-των-τριών-ιερα",
    "destination": "/nea/enimerosi-gia-ti-giorti-ton-trion-ierarchon-sto-scholeio-mas",
    "permanent": true
  },
  {
    "source": "/2024/02/09/ποιος-σκότωσε-το-σκύλο-τα-μεσάνυχτα",
    "destination": "/nea/poios-skotose-to-skylo-ta-mesanychta",
    "permanent": true
  },
  {
    "source": "/2024/02/09/αίσωπος-φτου-και-βγαίνω",
    "destination": "/nea/aisopos-ftou-kai-vgaino",
    "permanent": true
  },
  {
    "source": "/2024/02/15/το-φάντασμα-του-κάντερβιλ",
    "destination": "/nea/to-fantasma-tou-kantervil",
    "permanent": true
  },
  {
    "source": "/2024/02/15/αρχέλων",
    "destination": "/nea/archelon",
    "permanent": true
  },
  {
    "source": "/2024/02/15/όταν-το-σκουπίδι-ονειρεύεται-γίνεται",
    "destination": "/nea/otan-to-skoupidi-oneireyetai-ginetai-louloydi-tipota-den-einai-achristo",
    "permanent": true
  },
  {
    "source": "/2024/02/15/κοπή-βασιλόπιτας-στο-σχολείο",
    "destination": "/nea/kopi-vasilopitas-sto-scholeio",
    "permanent": true
  },
  {
    "source": "/2024/02/15/μπες-στα-παπούτσια-μου",
    "destination": "/nea/bes-sta-papoytsia-mou",
    "permanent": true
  },
  {
    "source": "/2024/02/15/σκιές-στο-πεντάγραμμο",
    "destination": "/nea/skies-sto-pentagrammo",
    "permanent": true
  },
  {
    "source": "/2024/02/15/η-ιστορία-της-γης",
    "destination": "/nea/i-istoria-tis-gis",
    "permanent": true
  },
  {
    "source": "/2024/02/16/ασφαλής-πλοήγηση-στο-διαδίκτυο",
    "destination": "/nea/asfalis-ploigisi-sto-diadiktyo",
    "permanent": true
  },
  {
    "source": "/2024/02/19/οδοντιατρικός-έλεγχος",
    "destination": "/nea/odontiatrikos-elenchos",
    "permanent": true
  },
  {
    "source": "/2024/02/22/τhink-up",
    "destination": "/nea/think-up",
    "permanent": true
  },
  {
    "source": "/2024/02/29/ο-γλεντζοφλέβαρος",
    "destination": "/nea/o-glentzoflevaros",
    "permanent": true
  },
  {
    "source": "/2024/02/29/science-is-fun",
    "destination": "/nea/science-is-fun",
    "permanent": true
  },
  {
    "source": "/2024/03/28/μαθαίνω-να-αγαπώ-τον-άνθρωπο",
    "destination": "/nea/mathaino-na-agapo-ton-anthropo",
    "permanent": true
  },
  {
    "source": "/2024/03/28/νικάμε-τη-βία-και-το-σχολικό-εκφοβισμό",
    "destination": "/nea/nikame-ti-via-kai-to-scholiko-ekfovismo",
    "permanent": true
  },
  {
    "source": "/2024/04/05/συμμετοχή-σε-επιμορφωτική-ημερίδα-κα",
    "destination": "/nea/symmetochi-se-epimorfotiki-imerida-kai-leitourgia-scholeiou",
    "permanent": true
  },
  {
    "source": "/2024/04/07/ημέρα-κατά-του-σχολικού-εκφοβισμού",
    "destination": "/nea/imera-kata-tou-scholikoy-ekfovismoy",
    "permanent": true
  },
  {
    "source": "/2024/04/08/τσικνοπέμπτη-2024-στο-8ο-δημοτικό",
    "destination": "/nea/tsiknopebti-2024-sto-8o-dimotiko",
    "permanent": true
  },
  {
    "source": "/2024/04/08/με-άλλα-μάτια",
    "destination": "/nea/me-alla-matia",
    "permanent": true
  },
  {
    "source": "/2024/04/16/άνοιξη",
    "destination": "/nea/anoixi",
    "permanent": true
  },
  {
    "source": "/2024/04/17/επίσκεψη-στο-μουσείο-μικρασιατικού-ε",
    "destination": "/nea/episkepsi-sto-mouseio-mikrasiatikoy-ellinismoy",
    "permanent": true
  },
  {
    "source": "/2024/04/17/επίσκεψη-στο-βυζαντινό-μουσείο",
    "destination": "/nea/episkepsi-sto-vyzantino-mouseio",
    "permanent": true
  },
  {
    "source": "/2024/04/17/βλέπουμε-το-φως-με-άλλα-μάτια",
    "destination": "/nea/vlepoume-to-fos-me-alla-matia",
    "permanent": true
  },
  {
    "source": "/2024/04/17/μουσείο-φυσικής-ιστορίας-γουλανδρή",
    "destination": "/nea/mouseio-fysikis-istorias-goulandri",
    "permanent": true
  },
  {
    "source": "/2024/04/23/επίσκεψη-στο-μέγαρο-μουσικής",
    "destination": "/nea/episkepsi-sto-megaro-mousikis",
    "permanent": true
  },
  {
    "source": "/2024/04/23/πρόγραμμα-εκπαιδευτικής-ρομποτικής",
    "destination": "/nea/programma-ekpaideftikis-robotikis-sto-scholeio-mas",
    "permanent": true
  },
  {
    "source": "/2024/04/25/επίσκεψη-στην-ακρόπολη",
    "destination": "/nea/episkepsi-stin-akropoli",
    "permanent": true
  },
  {
    "source": "/2024/04/25/γνωριμία-με-την-τέχνη-της-βιβλιοδεσία",
    "destination": "/nea/gnorimia-me-tin-techni-tis-vivliodesias",
    "permanent": true
  },
  {
    "source": "/2024/04/25/συμμετοχή-στο-φεστιβάλ-ρητορικής",
    "destination": "/nea/symmetochi-sto-festival-ritorikis",
    "permanent": true
  },
  {
    "source": "/2024/04/25/εκπαιδευτικεσ-επισκεψεισ-γ-τριμηνου-2024",
    "destination": "/nea/ekpaideftikes-episkepseis-g-triminou-2024",
    "permanent": true
  },
  {
    "source": "/2024/04/25/πασχαλινές-δημιουργίες-από-το-τμήμα-α2",
    "destination": "/nea/paschalines-dimiourgies-apo-to-tmima-a2-tou-scholeiou-mas",
    "permanent": true
  },
  {
    "source": "/2024/04/26/εκπαιδευτικεσ-επισκεψεισ-γ-τριμηνου",
    "destination": "/nea/choris-titlo-2",
    "permanent": true
  },
  {
    "source": "/2024/04/26/easter-egg-hunt",
    "destination": "/nea/easter-egg-hunt",
    "permanent": true
  },
  {
    "source": "/2024/04/26/κάλαντα-λαζάρου",
    "destination": "/nea/kalanta-lazarou",
    "permanent": true
  },
  {
    "source": "/2024/04/26/πασχαλινά-έθιμα",
    "destination": "/nea/paschalina-ethima",
    "permanent": true
  },
  {
    "source": "/2024/04/26/ραπουνζέλ-χωρίς-παραμύθι",
    "destination": "/nea/rapounzel-choris-paramythi",
    "permanent": true
  },
  {
    "source": "/2024/04/26/ευχές",
    "destination": "/nea/efches",
    "permanent": true
  },
  {
    "source": "/2024/05/27/πετυχαίνοντας-το-στόχο-μου",
    "destination": "/nea/petychainontas-to-stocho-mou",
    "permanent": true
  },
  {
    "source": "/2024/06/11/λειτουργία-σχολείου",
    "destination": "/nea/leitourgia-scholeiou",
    "permanent": true
  },
  {
    "source": "/2024/06/13/μάθημα-κυκλοφοριακής-αγωγής",
    "destination": "/nea/mathima-kykloforiakis-agogis",
    "permanent": true
  },
  {
    "source": "/2024/06/13/επίσκεψη-στη-βουλή",
    "destination": "/nea/episkepsi-sti-vouli",
    "permanent": true
  },
  {
    "source": "/2024/06/13/αθλητικές-δραστηριότητες",
    "destination": "/nea/athlitikes-drastiriotites",
    "permanent": true
  },
  {
    "source": "/2024/06/13/planet-physics",
    "destination": "/nea/planet-physics",
    "permanent": true
  },
  {
    "source": "/2024/06/13/goalball",
    "destination": "/nea/goalball",
    "permanent": true
  },
  {
    "source": "/2024/06/13/επίδοση-βαθμολογίας-και-τίτλων-προόδ",
    "destination": "/nea/epidosi-vathmologias-kai-titlon-proodou",
    "permanent": true
  },
  {
    "source": "/2024/06/13/τελετή-αποφοίτησης",
    "destination": "/nea/giorti-apofoitisis",
    "permanent": true
  },
  {
    "source": "/2024/06/14/μαθαίνω-να-παίζω-μαθαίνω-να-ζω",
    "destination": "/nea/mathaino-na-paizo-mathaino-na-zo",
    "permanent": true
  },
  {
    "source": "/2024/06/23/πιλοτικό-πρόγραμμα",
    "destination": "/nea/pilotiko-programma",
    "permanent": true
  },
  {
    "source": "/2024/09/05/θεσμός-σχολικού-τροχονόμου-2024-25",
    "destination": "/nea/thesmos-scholikoy-trochonomou-2024-25",
    "permanent": true
  },
  {
    "source": "/2024/09/07/λίστες-υλικών-2024-25",
    "destination": "/nea/listes-ylikon-2024-25",
    "permanent": true
  },
  {
    "source": "/2024/09/09/έναρξη-σχολικής-χρονιάς-αγιασμός",
    "destination": "/nea/enarxi-scholikis-chronias-agiasmos",
    "permanent": true
  },
  {
    "source": "/2024/09/22/ατομικό-δελτίο-υγείας",
    "destination": "/nea/atomiko-deltio-ygeias",
    "permanent": true
  },
  {
    "source": "/2024/09/27/εκπαιδευτικές-επισκέψεις￼",
    "destination": "/nea/ekpaideftikes-episkepseis-3",
    "permanent": true
  },
  {
    "source": "/2024/09/28/πανελλήνια-ημέρα-αθλητισμού",
    "destination": "/nea/panellinia-imera-athlitismoy",
    "permanent": true
  },
  {
    "source": "/2024/10/03/μουσείο-εθνικής-αντίστασης",
    "destination": "/nea/mouseio-ethnikis-antistasis",
    "permanent": true
  },
  {
    "source": "/2024/10/04/πρακτική-άσκηση-φοιτητών",
    "destination": "/nea/praktiki-askisi-foititon",
    "permanent": true
  },
  {
    "source": "/2024/10/05/λειτουργία-σχολικής-βιβλιοθήκης",
    "destination": "/nea/leitourgia-scholikis-vivliothikis",
    "permanent": true
  },
  {
    "source": "/2024/10/14/ιεπ",
    "destination": "/nea/iep",
    "permanent": true
  },
  {
    "source": "/2024/10/25/ενημέρωση-για-το-πρόγραμμα-εορτασμού",
    "destination": "/nea/enimerosi-gia-to-programma-eortasmoy-tis-epeteiou-tis-28is-oktovriou",
    "permanent": true
  },
  {
    "source": "/2024/10/26/οι-μαθητές-δημιούργησαν-για-τον-ελλην",
    "destination": "/nea/oi-mathites-dimioyrgisan-gia-ton-ellinismo-tis-anatolis-kai",
    "permanent": true
  },
  {
    "source": "/2024/10/28/ο-εορτασμός-της-28ης-οκτωβρίου-στο-σχολ-2",
    "destination": "/nea/o-eortasmos-tis-28is-oktovriou-sto-scholeio-mas",
    "permanent": true
  },
  {
    "source": "/2024/10/31/ιστορική-έκθεση-1974-1944-η-αθήνα-γιορτάζει",
    "destination": "/nea/istoriki-ekthesi-1974-1944-i-athina-giortazei-tin-eleftheria-tis",
    "permanent": true
  },
  {
    "source": "/2024/11/07/κανονισμός-σχολείου",
    "destination": "/nea/kanonismos-scholeiou",
    "permanent": true
  },
  {
    "source": "/2024/11/08/τα-γενέθλια",
    "destination": "/nea/ta-genethlia",
    "permanent": true
  },
  {
    "source": "/2024/11/14/ενημέρωση-για-τον-εορτασμό-της-17-νοέμβρ",
    "destination": "/nea/enimerosi-gia-ton-eortasmo-tis-17-noemvri-sto-scholeio-mas",
    "permanent": true
  },
  {
    "source": "/2024/11/17/η-επέτειος-του-πολυτεχνείου-στο-σχολε",
    "destination": "/nea/i-epeteios-tou-polytechneiou-sto-scholeio-mas",
    "permanent": true
  },
  {
    "source": "/2024/11/25/ώρες-επικοινωνίας-με-το-διδακτικό-προ",
    "destination": "/nea/ores-epikoinonias-me-to-didaktiko-prosopiko",
    "permanent": true
  },
  {
    "source": "/2024/11/27/τα-στολίδια-μας-ταξιδεύουν",
    "destination": "/nea/ta-stolidia-mas-taxideyoun",
    "permanent": true
  },
  {
    "source": "/2024/12/02/μετρώντας-αντίστροφα-για-τα-χριστούγ",
    "destination": "/nea/metrontas-antistrofa-gia-ta-christoygenna",
    "permanent": true
  },
  {
    "source": "/2024/12/17/επίδοση-βαθμολογίας-ατριμήνου",
    "destination": "/nea/epidosi-vathmologias-atriminou",
    "permanent": true
  },
  {
    "source": "/2024/12/19/μπαίνοντας-στο-πνεύμα-των-χριστουγέν",
    "destination": "/nea/bainontas-sto-pneyma-ton-christougennon",
    "permanent": true
  },
  {
    "source": "/2024/12/20/επίσκεψη-στο-μουσείο-οίνου-μάρκου",
    "destination": "/nea/episkepsi-sto-mouseio-oinou-markou",
    "permanent": true
  },
  {
    "source": "/2024/12/20/επίσκεψη-στο-μουσείο-φυσικής-ιστορία",
    "destination": "/nea/episkepsi-sto-mouseio-fysikis-istorias-goulandri",
    "permanent": true
  },
  {
    "source": "/2024/12/20/η-αλίκη-στη-χώρα-των-θαυμάτων",
    "destination": "/nea/i-aliki-sti-chora-ton-thafmaton",
    "permanent": true
  },
  {
    "source": "/2024/12/21/ποιος-σκότωσε-τον-σκύλο-τα-μεσάνυχτα",
    "destination": "/nea/poios-skotose-ton-skylo-ta-mesanychta",
    "permanent": true
  },
  {
    "source": "/2024/12/31/secret-santa-2",
    "destination": "/nea/secret-santa-2",
    "permanent": true
  },
  {
    "source": "/2024/12/31/χριστουγεννιάτικα-στολίδια",
    "destination": "/nea/christougenniatika-stolidia",
    "permanent": true
  },
  {
    "source": "/2024/12/31/δύο-χρόνια-σοφοθήκη",
    "destination": "/nea/dyo-chronia-sofothiki",
    "permanent": true
  },
  {
    "source": "/2024/12/31/aνάγνωση-παραμυθιών",
    "destination": "/nea/anagnosi-paramythion",
    "permanent": true
  },
  {
    "source": "/2025/01/17/επίσκεψη-συγγραφέα-στο-σχολείο-μας",
    "destination": "/nea/christougenniatiki-giorti-vtaxis",
    "permanent": true
  },
  {
    "source": "/2025/01/20/επίσκεψη-συγγραφέα-στο-σχολείο-μας-2",
    "destination": "/nea/episkepsi-syngrafea-sto-scholeio-mas",
    "permanent": true
  },
  {
    "source": "/2025/01/22/εκπαιδευτικές-επισκέψεις-βτριμήνου",
    "destination": "/nea/ekpaideftikes-episkepseis-vtriminou",
    "permanent": true
  },
  {
    "source": "/2025/01/29/ευχές-και-κάλαντα",
    "destination": "/nea/efches-kai-kalanta",
    "permanent": true
  },
  {
    "source": "/2025/01/29/ευχές-και-κάλαντα-2",
    "destination": "/nea/efches-kai-kalanta-2",
    "permanent": true
  },
  {
    "source": "/2025/01/30/τρίποντα-στα-σχολεία",
    "destination": "/nea/triponta-sta-scholeia",
    "permanent": true
  },
  {
    "source": "/2025/01/31/κοπή-βασιλόπιτας-στο-σχολείο-μας",
    "destination": "/nea/kopi-vasilopitas-sto-scholeio-mas",
    "permanent": true
  },
  {
    "source": "/2025/02/05/πώς-γιορτάζουν-την-υπαπαντή-οι-γάλλοι",
    "destination": "/nea/pos-giortazoun-tin-ypapanti-oi-galloi",
    "permanent": true
  },
  {
    "source": "/2025/02/07/επίσκεψη-στο-ο-α-κ-α",
    "destination": "/nea/episkepsi-sto-o-a-k-a",
    "permanent": true
  },
  {
    "source": "/2025/02/11/βουτιά-στην-ιστορία",
    "destination": "/nea/voutia-stin-istoria",
    "permanent": true
  },
  {
    "source": "/2025/02/12/επίσκεψη-συγγραφέως-στο-σχολείο-μας",
    "destination": "/nea/episkepsi-syngrafeos-sto-scholeio-mas",
    "permanent": true
  },
  {
    "source": "/2025/02/16/το-σχολείο-μας-αλλάζει",
    "destination": "/nea/to-scholeio-mas-allazei",
    "permanent": true
  },
  {
    "source": "/2025/03/06/εγγραφεσ-α-δημοτικου-2025-2026",
    "destination": "/nea/engrafes-a-dimotikou-2025-2026",
    "permanent": true
  },
  {
    "source": "/2025/03/10/εκπαιδευτικές-επισκέψεις-3",
    "destination": "/nea/ekpaideftikes-episkepseis-4",
    "permanent": true
  },
  {
    "source": "/2025/04/01/τα-παιδιά-μας-υποδέχτηκαν-την-άνοιξη",
    "destination": "/nea/ta-paidia-mas-ypodechtikan-tin-anoixi",
    "permanent": true
  },
  {
    "source": "/2025/04/07/θεατρική-παράσταση",
    "destination": "/nea/theatriki-parastasi",
    "permanent": true
  },
  {
    "source": "/2025/05/14/αρχιτεκτονική-του-χθες-και-του-σήμερα",
    "destination": "/nea/architektoniki-tou-chthes-kai-tou-simera-se-ellada-kai-italia",
    "permanent": true
  },
  {
    "source": "/2025/05/14/παγκόσμια-μέρα-βιβλίου",
    "destination": "/nea/pagkosmia-mera-vivliou",
    "permanent": true
  },
  {
    "source": "/2025/05/14/τετράλιζα",
    "destination": "/nea/tetraliza",
    "permanent": true
  },
  {
    "source": "/2025/05/14/γνωριμία-με-το-άθλημα-του-μπέιζμπολ5",
    "destination": "/nea/gnorimia-me-to-athlima-tou-beizbol5",
    "permanent": true
  },
  {
    "source": "/2025/05/23/επίσκεψη-των-παππούδων-στο-σχολείο-μα",
    "destination": "/nea/episkepsi-ton-pappoydon-sto-scholeio-mas",
    "permanent": true
  },
  {
    "source": "/2025/05/23/7ο-φεστιβάλ-ρητορικής-σκέφτομαι-εκφρ",
    "destination": "/nea/7o-festival-ritorikis-skeftomai-ekfrazomai-epikoinono-milontas-gia-ta",
    "permanent": true
  },
  {
    "source": "/2025/05/23/τμήμα-ένταξης",
    "destination": "/nea/tmima-entaxis",
    "permanent": true
  },
  {
    "source": "/2025/05/23/τα-νέα-των-δημοσιογράφων-του-β1",
    "destination": "/nea/ta-nea-ton-dimosiografon-tou-v1",
    "permanent": true
  },
  {
    "source": "/2025/09/04/πρόσκληση-για-σχολικό-τροχονόμο",
    "destination": "/nea/prosklisi-gia-scholiko-trochonomo",
    "permanent": true
  },
  {
    "source": "/2025/09/08/πρώτο-κουδούνι",
    "destination": "/nea/proto-koudoyni",
    "permanent": true
  },
  {
    "source": "/2025/09/19/εκ-νέου-εγγραφές-στο-ολοήμερο-σχολείο",
    "destination": "/nea/ek-neou-engrafes-sto-oloimero-scholeio",
    "permanent": true
  },
  {
    "source": "/2025/09/25/λειτουργία-ολοήμερου-σχολείου",
    "destination": "/nea/leitourgia-oloimerou-scholeiou",
    "permanent": true
  },
  {
    "source": "/2025/09/26/λειτουργια-ολοημερου",
    "destination": "/nea/leitourgia-oloimerou",
    "permanent": true
  },
  {
    "source": "/2025/09/26/σχολική-ψυχολόγος",
    "destination": "/nea/scholiki-psychologos-2",
    "permanent": true
  },
  {
    "source": "/2025/09/30/απεργία",
    "destination": "/nea/apergia",
    "permanent": true
  },
  {
    "source": "/2025/10/02/ολοήμερο",
    "destination": "/nea/oloimero",
    "permanent": true
  },
  {
    "source": "/2025/10/08/δίωρη-στάση-εργασίας",
    "destination": "/nea/diori-stasi-ergasias",
    "permanent": true
  },
  {
    "source": "/2025/10/09/λειτουργία-ολοήμερου-σχολείου-2",
    "destination": "/nea/leitourgia-oloimerou-scholeiou-2",
    "permanent": true
  },
  {
    "source": "/2025/10/13/εκπαιδευτικές-επισκέψεις-4",
    "destination": "/nea/ekpaideftikes-episkepseis-5",
    "permanent": true
  },
  {
    "source": "/2025/10/13/λειτουργία-ολοήμερου-σχολείου-3",
    "destination": "/nea/leitourgia-oloimerou-scholeiou-3",
    "permanent": true
  },
  {
    "source": "/2025/10/15/λειτουργία-ολοήμερου-σχολείου-4",
    "destination": "/nea/leitourgia-oloimerou-scholeiou-4",
    "permanent": true
  },
  {
    "source": "/2025/10/21/λειτουργία-ολοήμερου-σχολείου-5",
    "destination": "/nea/leitourgia-oloimerou-scholeiou-5",
    "permanent": true
  },
  {
    "source": "/2025/10/22/επίσκεψη-στο-κέντρο-θαλάσσιων-χελωνώ",
    "destination": "/nea/episkepsi-sto-kentro-thalassion-chelonon",
    "permanent": true
  },
  {
    "source": "/2025/10/24/ενημέρωση-για-τις-εορταστικές-εκδηλώ",
    "destination": "/nea/enimerosi-gia-tis-eortastikes-ekdiloseis-tis-28is-oktovriou",
    "permanent": true
  },
  {
    "source": "/2025/10/24/ενημέρωση-για-το-πρόγραμμα-εορτασμού-2",
    "destination": "/nea/enimerosi-gia-to-programma-eortasmoy-tis-epeteiou-tis-28is-oktovriou-2",
    "permanent": true
  },
  {
    "source": "/2025/11/05/λειτουργία-ολοήμερου-δημοτικού-σχολ",
    "destination": "/nea/leitourgia-oloimerou-dimotikoy-scholeiou",
    "permanent": true
  },
  {
    "source": "/2025/12/22/επίσκεψη-στο-αt20-sport-park",
    "destination": "/nea/episkepsi-sto-at20-sport-park",
    "permanent": true
  },
  {
    "source": "/2026/01/23/εκπαιδευτικές-επισκέψεις-5",
    "destination": "/nea/ekpaideftikes-episkepseis-6",
    "permanent": true
  },
  {
    "source": "/2026/02/18/θεατρική-παράσταση-《το-κύμα》",
    "destination": "/nea/theatriki-parastasi-to-kyma",
    "permanent": true
  },
  {
    "source": "/2026/02/18/σχολή-χορούχορός-ρυθμόςκίνηση",
    "destination": "/nea/scholi-choroy-choros-rythmos-kinisi",
    "permanent": true
  },
  {
    "source": "/2026/02/26/εγγραφές-μαθητών-α-δημοτικού",
    "destination": "/nea/engrafes-mathiton-a-dimotikoy",
    "permanent": true
  },
  {
    "source": "/2026/03/17/επίδοση-ελέγχων-βτριμήνου-και-ενημέρ",
    "destination": "/nea/epidosi-elenchon-vtriminou-kai-enimerosi",
    "permanent": true
  },
  {
    "source": "/2026/04/23/living-values-education-program",
    "destination": "/nea/living-values-education-program",
    "permanent": true
  },
  {
    "source": "/2026/04/23/βιωματική-δράση",
    "destination": "/nea/viomatiki-drasi",
    "permanent": true
  },
  {
    "source": "/2026/05/10/εκπαιδευτικές-επισκέψεις-6",
    "destination": "/nea/ekpaideftikes-episkepseis-7",
    "permanent": true
  },
  {
    "source": "/2026/05/27/συμμετοχή-στο-φεστιβάλ-ρητορικής-2",
    "destination": "/nea/symmetochi-sto-festival-ritorikis-2",
    "permanent": true
  },
  {
    "source": "/2026/05/27/eπίσκεψη-της-φιλαρμονικής-αγίας-παρασ",
    "destination": "/nea/episkepsi-tis-filarmonikis-agias-paraskefis-sto-scholeio-mas",
    "permanent": true
  },
  {
    "source": "/2026/05/27/εκδρομή-στον-υμηττό",
    "destination": "/nea/ekdromi-ston-ymitto",
    "permanent": true
  },
  {
    "source": "/2026/09/01/αγιασμός-παρασκευή-11-σεπτεμβρίου-2026",
    "destination": "/nea/agiasmos-paraskefi-11-septemvriou-2026",
    "permanent": true
  },
  {
    "source": "/sample-page",
    "destination": "/to-scholeio-mas",
    "permanent": true
  },
  {
    "source": "/επικοινωνία",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/ωράριο-λειτουργίας",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/1286-2",
    "destination": "/",
    "permanent": true
  },
  {
    "source": "/εκπαιδευτικεσ-επισκεψεισ-γ-τριμηνου-2024",
    "destination": "/",
    "permanent": true
  }
];
